[profile.default]
solc = '0.8.17'
via_ir = true
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config